spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringSecurityExample
    username: postgres
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update